global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
  - static_configs:
      - targets:
        - alertmanger:9093


scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets:
          - 'prometheus:9090'
          - 'alertmanager:9093'
          - 'grafana:3000'
  - job_name: 'flask-app'
    scrape_interval: 5s
    static_configs:
      - targets:
          - 'flask-app:8000'
